export const Galleries = [{
    'galleryId': '1',
    'title': 'Sumin',
    'dateCreated': '1933-06-15T00:00:00+00:00',
    'thumbUrl': './assets/img/Sumin.jpg',
    'description': 'Szkoła w Suminie przed wojną',
    'tags': [],
    'photos': [],
}, {
    'galleryId': '2',
    'title': 'Sucumin',
    'dateCreated': '2017-08-15T00:00:00+00:00',
    'thumbUrl': './assets/img/Sucumin.jpg',
    'description': 'Stary pałac w Sucuminie',
    'tags': [],
    'photos': [],
}, {
    'galleryId': '3',
    'title': 'Rokocin',
    'dateCreated': '2017-03-15T00:00:00+00:00',
    'thumbUrl': './assets/img/Rokocin.jpg',
    'description': 'Dwór w Rokocinie',
    'tags': [],
    'photos': [],
}, {
    'galleryId': '4',
    'title': 'Koteże',
    'dateCreated': '2019-07-15T00:00:00+00:00',
    'thumbUrl': './assets/img/Koteże.jpg',
    'description': 'Sklep u Danki',
    'tags': [],
    'photos': [],
}, {
    'galleryId': '5',
    'title': 'Skarszewy',
    'dateCreated': '2022-09-15T00:00:00+00:00',
    'thumbUrl': './assets/img/Skarszewy.jpg',
    'description': 'Chyba rynek, niewiem nie znam się',
    'tags': [],
    'photos': [],
},
{
    'galleryId': '6',
    'title': 'Starogard Gdański',
    'dateCreated': '2025-12-15T00:00:00+00:00',
    'thumbUrl': './assets/img/Starogard.jpg',
    'description': 'Rynek',
    'tags': [],
    'photos': [],
},  ]